### ISSUE TITLE
Solidity contract with boolean array inputs are wrongly encoded

### ISSUE THREAD

**Issue by leayingly** [FISCO-BCOS/nodejs-sdk#111]
Function input encoder fails for 2D boolean array.

Take following example:

1. Add following codes to test contract 
/test/contracts/v4/HelloWorld.sol
```
    function healthCheck2(bool[2] memory a, bool[2] memory b) public returns (bool) {   
        return b[0];
    }
```

2. Update test case 
/test/test_HelloWorld.js
```JS
    it('healthCheck2', async () => {

        // Attemp 1
        let ret = await helloWorld.healthCheck2([[false, false], [false, false]]);
        // AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:
        // assert(isArray(type) && type.length === data.length)
        //     + expected - actual
        //     -false
        //     +true
        //     at formalize (packages/api/common/web3lib/web3sync.js:69:9)
        //     at encodeParams (packages/api/common/web3lib/web3sync.js:100:14)
        //     at getTxData (packages/api/common/web3lib/web3sync.js:116:22)
        //     at getSignTx (packages/api/common/web3lib/web3sync.js:139:18)
        //     at Web3jService._rawTransaction (packages/api/web3j/web3jService.js:184:22)
        //     at Web3jService.sendRawTransaction (packages/api/web3j/web3jService.js:203:37)
        //     at async Context.<anonymous> (test/test_HelloWorld.js:76:19)

        // Attempt 2
        let ret = await helloWorld.healthCheck2('[[false,false],[false,false]]');
        // AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

        // assert(isArray(type) && type.length === data.length)
      
        //     + expected - actual
      
        //     -false
        //     +true
            
        //     at formalize (packages/api/common/web3lib/web3sync.js:69:9)
        //     at encodeParams (packages/api/common/web3lib/web3sync.js:100:14)
        //     at getTxData (packages/api/common/web3lib/web3sync.js:116:22)
        //     at getSignTx (packages/api/common/web3lib/web3sync.js:139:18)
        //     at Web3jService._rawTransaction (packages/api/web3j/web3jService.js:184:22)
        //     at Web3jService.sendRawTransaction (packages/api/web3j/web3jService.js:203:37)
        //     at async Context.<anonymous> (test/test_HelloWorld.js:94:19)

        // This will fail for attempt 2
        should.equal(ret[0], false);
    });
```

**Comment by vita-dounai** [comment]
面白いですね～
