### ISSUE TITLE
'./cli.js getPeers' return error

### ISSUE THREAD

**Issue by wuyahuang** [FISCO-BCOS/nodejs-sdk#118]
Client:
node v10.0.0 (macOS big sur)

Server:
fisco 2.7.1 (CentOS 7.4)

try to getPeers
`./cli.js getPeers`

return error:
```
(node:97324) UnhandledPromiseRejectionWarning: Error: error:100D7010:elliptic curve routines:eckey_pub_decode:EC lib
    at Object.createSecureContext (_tls_common.js:124:17)
    at createNewSocket (/nodejs-sdk/packages/api/common/network/channelPromise.js:187:27)
```

config.json
```
{
  "encryptType": "SM_CRYPTO",
  "accounts": {
    "alice": {
      "type": "pem",
      "value": "./accounts/alice.pem"
    }
  },
  "nodes": [
    {
      "ip": "127.0.0.1",
      "port": "20200"
    }
  ],
  "authentication": {
    "key": "./authentication/gmsdk.key",
    "cert": "./authentication/gmsdk.crt",
    "ca": "./authentication/gmca.crt"
  },
  "groupID": 1,
  "chainID": 1,
  "timeout": 10000
}
```

**Comment by vita-dounai** [comment]
应该是证书的类型不对

**Comment by wuyahuang** [comment]
在微信群跟微众的开发确认过了，nodejs SDK 目前不支持国密 SSL。
